### ISSUE TITLE
Add SVE support

### ISSUE THREAD

**Issue by ericvh** [parsa-epfl/qflex#11]

**Comment by Hnefi** [comment]
Hi @ericvh, I just wanted to let you know that we have finally released our QFlex timing model, which allows cycle-level simulation of both the CPU pipeline and a detailed cache hierarchy! You can find it in the master branch of the repo, and a guide on how to use it is available on the website qflex.epfl.ch.

We've seen a lot of SVE instructions being used by libraries in our debugging work (e.g., Google protobuf and even in libc), so this is definitely a feature on our list of additions. We welcome any contributions you might have to the simulator tool, if you are interested in working with us on supporting SVE!
