### ISSUE TITLE
deprecated-declarations on hw-libusb.c

### ISSUE THREAD

**Issue by ahmadsb101** [parsa-epfl/qflex#20]
`./build_qemu.sh -emulation` returns this error below:
```
hw/usb/host-libusb.c: In function ‘usb_host_init’:
hw/usb/host-libusb.c:294:5: error: ‘libusb_set_debug’ is deprecated: Use libusb_set_option instead [-Werror=deprecated-declarations] libusb_set_debug(ctx, loglevel);
                                                            ^~~~~~~~~~~~~~~~
In file included from hw/usb/host-libusb.c:84:
/usr/include/libusb-1.0/libusb.h:1300:18: note: declared here
 void LIBUSB_CALL libusb_set_debug(libusb_context *ctx, int level);
                                   ^~~~~~~~~~~~~~~~
```

**Comment by neo-apz** [comment]
As this is related to QEMU, could you please close this issue and open a new one under our [qemu repo](https://github.com/parsa-epfl/qemu)?
Also, please give us more information about your OS, compiler, and libusb versions for reproducibility.

**Comment by ahmadsb101** [comment]
Thanks for your notice. 
My OS is Linux debian 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
GCC version is 8.3.0
libusb version is 2:0.1.12-32

**Comment by neo-apz** [comment]
We just updated our QEMU and [applied a patch](https://github.com/parsa-epfl/qemu/commit/21581ca91524ce8bedbf656ef643c1b81cb2d4bb#diff-88181ec7fe1e31f3e0954d0f655aa7c3) that resolves this issue.
Please update your local QEMU.
