### ISSUE TITLE
Too low LLC MPKI on pointer chase benchmark

### ISSUE THREAD

**Issue by branylagaffe** [parsa-epfl/qflex#35]
**I want** to test statistics of KeenKraken
**So that** we can assert the quality of the statistics of KeenKraken

**Specification:**
1. Micro benchmark are identified, and added to the base image
2. Test have been run and match micro benchmark expectation

**Tasks:**
- [x] Add microbenchmark

**Comment by branylagaffe** [comment]
I have added to the base images multiple micro benchmark which can be bundled with Buildroot.

- Dropwatch
- Hyperfine
- mbw
- perftest
- ramspeed
- stress
- stress-ng
- whetstone

**Comment by branylagaffe** [comment]
- [x] Use debug mode
- [x] Add VA Translation check

**Comment by branylagaffe** [comment]
@ayanchak1508 Could post maybe your graph here ?
To keep a trace on how to reproduce and test for this + CLI command used to run the benchmark

**Comment by ayanchak1508** [comment]
This is the plot:
![image](https://github.com/user-attachments/assets/ad9dc27d-8c66-4a6f-989c-7f164a106fb4)

I just run:
`./runq images/alp-trace` where alp-trace is a personal config file that runs Alpine Linux. (attached)

The code for the microbenchmark is also present in the zip.
[git.zip](https://github.com/user-attachments/files/16441504/git.zip)

**Comment by branylagaffe** [comment]
@ayanchak1508 Please explain what happened

**Comment by branylagaffe** [comment]
Not using `icount` made QEMU use host time, therefore was privileged kernel timer interrupt instead of processing user space instruction. The benchmark was bc. of this false
