### ISSUE TITLE
Is there any document about design?

### ISSUE THREAD

**Issue by dzwduan** [parsa-epfl/qflex#36]
I only found how to build doc，but design related api no document

**Comment by branylagaffe** [comment]
Hey @dzwduan thanks for your interest. 
<sub>Sadly, the only piece of "design" documentation left to me is on a decaying sheet of A4 paper. </sub>

> [!NOTE]
> This tutorial from 2005 still explain some baseline that may still be relevant: https://parsa.epfl.ch/simflex/doc/SimFlex-tutorial-micro2005.pdf

**Comment by dzwduan** [comment]
Thanks branylagaffe, I also found memory links when i try to run both release and debug mode, I tried trace and timing, they all failed. 
![d5e3d45618babb339e1fe2fcd9f4797](https://github.com/user-attachments/assets/2073d729-4c35-4783-8a97-9cff66a00c53)

**Comment by branylagaffe** [comment]
@dzwduan looks like you got an issue with the address sanitizer (libasan), for some unknown reason this does not work consistently on every machine.

I recommand to disable libasan by removing  `--extra-cflags="-fsanitize=address" ` in `build.sh` and
`-fsanitize=address` from `flexus/CMakeLists.txt`

**Comment by branylagaffe** [comment]
FYI, the latest branch for `qflex` is **next**, also pull the submodule regularly with `git submodule --update --recursive --remote` because I update regularly the branch with commiting the change QFlex repo

**Comment by dzwduan** [comment]
Thanks
