### ISSUE TITLE
upcoming release 

### ISSUE THREAD

**Issue by Jeongseob** [parsa-epfl/qflex#5]
Hi QFlex team,

I am currently exploring a new architectural simulator for my own research. I am just wondering whether QFlex with a timing model will be released soon or not. I couldn't find any news in the official website since April.

Thanks,
Jeongseob

**Comment by katetsu** [comment]
Hello Jeongseob,

We are working on an ARM64 timing model and the plan is to release it as soon as we have it. We already have a Trace model as you have seen on our wesbite.

Cheers
Hoss
