### ISSUE TITLE
What does the preload_system_width file mean?

### ISSUE THREAD

**Issue by Jeongseob** [parsa-epfl/qflex#6]
Hi All,

While trying to use QFlex with a snapshot image, I am getting an error from the `run_instanch.sh` as follows. I did not get any error when creating the snapshot and I was able to look at that the snapshot has been created by using the qemu-img command.

```
$ ./run_instance.sh -tr -lo=test_snapshot

+ printf './run_instance.sh:198: \033[0;31mERROR:\033[0m File /home/jeongseob/qflex/scripts/preload_system_width exists!\n'
./run_instance.sh:198: ERROR: File /home/jeongseob/qflex/scripts/preload_system_width exists!
+ exit 1 
```

The ```preload_system_width``` file contains 4 as below.

```
$ cat preload_system_width
4
```

BTW, I would like to get the memory access trace without the full functional simulation. Can you advise me how I can get the trace if possible?

Thanks,
Jeongseob

**Comment by ustiugov** [comment]
Hi Jeongseob,
This is a temporary file generated by QFlex in trace mode, and removed after successful termination of run_instance.sh.
Feel free to remove it.

Regards,
Dmitrii

**Comment by ustiugov** [comment]
Regarding memory trace generation, you could insert your tracing code in the following file:
https://github.com/parsa-epfl/qflex/blob/master/flexus/components/DecoupledFeederQEMU/QemuTracer.cpp#L242
There you can print types of memory instructions and their other attributes (address, user/kernel space, etc)
Then, here are the steps to get a trace:
* Boot a virtual machine with QFlex in functional mode (no trace)
* Run your target application inside it
* Save a snapshot
* Start QFlex in trace mode with your instrumented code.

I hope it helps.

Regards,
Dmitrii

P.S.
I am not sure I understood your comment regarding getting trace "without the full functional simulation". Can you elaborate on this?

**Comment by Jeongseob** [comment]
Hi @ustiugov ,

I meant that I do not want to simulate any things like cache, TLBs, etc because I am just interested in full memory accesses before going to L1 I/D cache. I expected simulating those structures may take a while. So I just want to save the cycles for my purpose.

Thanks for your suggestion. Btw, do I need to boot a virtual machine with QFlex to get a trace? I expect that QFlex will be only required on starting from a snapshot. 

I will be updating this issue after removing the temporary file and run the script again to load a snapshot with qflex.

Thanks,
Jeongseob

**Comment by ustiugov** [comment]
Hi Jeongseob,

Currently, neither Qemu nor QFlex have tracing instrumentation, so you need to either instrument Qemu itself or Qflex (like I described). I would suggest the latter as it is easier implementation-wise although it is about 50x slower than just Qemu (QFlex in emulation mode).

By booting in QFlex, I meant booting with QFlex without trace mode (i.e., booting with our version of Qemu). Then you have to load the snapshot you saved in Qflex _with_ trace mode (-tr). 

Regards,
Dmitrii

**Comment by Jeongseob** [comment]
Hi Dmitrii,

Thanks for your explanation. I agree with your suggestion. It will be much more easier than hacking the Qemu. 

After deleting the `preload_system_width` file, it seems working. I am able to see the messages like below. I think I can close this issue.

```
Decoupled feeder intialized? START...60 <flexus.cpp:316> {0}- Timestamp: Tue Nov 28 19:49:26 2017

Hello decouple feeder!

(omit)

Exiting because of break_simulation
With exit message: Reached the end of the simulation

```

Thanks,
Jeongseob
